// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RsvpStatus.
const (
	Accepted RsvpStatus = "accepted"
	Declined RsvpStatus = "declined"
	Pending  RsvpStatus = "pending"
)

// Valid indicates whether the value is a known member of the RsvpStatus enum.
func (e RsvpStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Declined:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt time.Time          `json:"createdAt"`
	Date      time.Time          `json:"date"`
	Id        openapi_types.UUID `json:"id"`
	Location  *string            `json:"location,omitempty"`
	Name      string             `json:"name"`
}

// Guest defines model for Guest.
type Guest struct {
	CreatedAt  time.Time            `json:"createdAt"`
	Email      *openapi_types.Email `json:"email,omitempty"`
	EventId    openapi_types.UUID   `json:"eventId"`
	Id         openapi_types.UUID   `json:"id"`
	Name       string               `json:"name"`
	RsvpStatus RsvpStatus           `json:"rsvpStatus"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Date     time.Time `json:"date"`
	Location *string   `json:"location,omitempty"`
	Name     string    `json:"name"`
}

// NewGuest defines model for NewGuest.
type NewGuest struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	Name       string               `json:"name"`
	RsvpStatus *RsvpStatus          `json:"rsvpStatus,omitempty"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// RsvpStatus defines model for RsvpStatus.
type RsvpStatus string

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// GuestId defines model for GuestId.
type GuestId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = NewUser

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = NewEvent

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = NewEvent

// CreateGuestJSONRequestBody defines body for CreateGuest for application/json ContentType.
type CreateGuestJSONRequestBody = NewGuest

// UpdateGuestJSONRequestBody defines body for UpdateGuest for application/json ContentType.
type UpdateGuestJSONRequestBody = NewGuest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Exchange credentials for a JWT
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// RegisterUser Register a new user
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// ListEvents List all events
	// (GET /events)
	ListEvents(w http.ResponseWriter, r *http.Request)
	// CreateEvent Create an event
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// DeleteEvent Delete an event
	// (DELETE /events/{eventId})
	DeleteEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// GetEvent Get a single event
	// (GET /events/{eventId})
	GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// UpdateEvent Replace an event
	// (PUT /events/{eventId})
	UpdateEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// ListGuests List guests for an event
	// (GET /events/{eventId}/guests)
	ListGuests(w http.ResponseWriter, r *http.Request, eventId EventId)
	// CreateGuest Add a guest to an event
	// (POST /events/{eventId}/guests)
	CreateGuest(w http.ResponseWriter, r *http.Request, eventId EventId)
	// DeleteGuest Remove a guest
	// (DELETE /events/{eventId}/guests/{guestId})
	DeleteGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId)
	// GetGuest Get a single guest
	// (GET /events/{eventId}/guests/{guestId})
	GetGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId)
	// UpdateGuest Replace a guest
	// (PUT /events/{eventId}/guests/{guestId})
	UpdateGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Exchange credentials for a JWT
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterUser Register a new user
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEvents List all events
// (GET /events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateEvent Create an event
// (POST /events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteEvent Delete an event
// (DELETE /events/{eventId})
func (_ Unimplemented) DeleteEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetEvent Get a single event
// (GET /events/{eventId})
func (_ Unimplemented) GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateEvent Replace an event
// (PUT /events/{eventId})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListGuests List guests for an event
// (GET /events/{eventId}/guests)
func (_ Unimplemented) ListGuests(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateGuest Add a guest to an event
// (POST /events/{eventId}/guests)
func (_ Unimplemented) CreateGuest(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteGuest Remove a guest
// (DELETE /events/{eventId}/guests/{guestId})
func (_ Unimplemented) DeleteGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetGuest Get a single guest
// (GET /events/{eventId}/guests/{guestId})
func (_ Unimplemented) GetGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateGuest Replace a guest
// (PUT /events/{eventId}/guests/{guestId})
func (_ Unimplemented) UpdateGuest(w http.ResponseWriter, r *http.Request, eventId EventId, guestId GuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGuests operation middleware
func (siw *ServerInterfaceWrapper) ListGuests(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGuests(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGuest operation middleware
func (siw *ServerInterfaceWrapper) CreateGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGuest(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGuest operation middleware
func (siw *ServerInterfaceWrapper) DeleteGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// ------------- Path parameter "guestId" -------------
	var guestId GuestId

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", chi.URLParam(r, "guestId"), &guestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGuest(w, r, eventId, guestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGuest operation middleware
func (siw *ServerInterfaceWrapper) GetGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// ------------- Path parameter "guestId" -------------
	var guestId GuestId

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", chi.URLParam(r, "guestId"), &guestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGuest(w, r, eventId, guestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGuest operation middleware
func (siw *ServerInterfaceWrapper) UpdateGuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// ------------- Path parameter "guestId" -------------
	var guestId GuestId

	err = runtime.BindStyledParameterWithOptions("simple", "guestId", chi.URLParam(r, "guestId"), &guestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGuest(w, r, eventId, guestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/events/{eventId}", wrapper.DeleteEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{eventId}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{eventId}", wrapper.UpdateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{eventId}/guests", wrapper.ListGuests)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{eventId}/guests", wrapper.CreateGuest)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/events/{eventId}/guests/{guestId}", wrapper.DeleteGuest)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{eventId}/guests/{guestId}", wrapper.GetGuest)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{eventId}/guests/{guestId}", wrapper.UpdateGuest)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fldc5s4F/4rGr3vRTtDjbPtRZe7NOt6su22HSedvcj4QoFjUAsSlYRTb4b/vqMPDMRg7Dh2s3c2ks7H",
	"c57zIbjHIc9yzoApiYN7nBNBMlAgzL/JEpi6jPRPynCAc6IS7GFGMsABBrfqYQE/CiogwoESBXhYhglk",
	"RB9bcJERhQNcFFTvVKtcH5VKUBbjsvTwtADZryN2q4foKPVhmXMmwXj1jkQz+KEF638hZwqY+UnyPKUh",
	"UZQz/5vkTD+r1fxfwAIH+H9+jZhvV6U/EYILqyoCGQqaayE4wJdsSVIaIeEUlh7+xNV7XrDo+MpnIHkh",
	"QkCMK7QwOksPf2WkUAkX9B84gQ1/USkpixEXiDosQgERMEVJKg0DnAyt4qKxpNkoeA5CURs3yAhNWwG3",
	"TzYi7uGcSHnHhfFvk3I1lW7WItYn5mtx/PYbhCZk1rsNgzKQksQwrKTa2Cl76cBvyw4FEAXRuWo5HBEF",
	"rxTNoMtpvbj7bhrtkDseTrnlQ4eTVZIOeW8Em63ORq/hXRck0yo3D4ZkD8pAXesGQdkRux54PCzkMr9S",
	"RBVyKK9m9c5OWOsa7ABuiB6C+SOPKZu5ytiRbj9zKkDuA7fi34ENE8Ju8xoausz7BHc9ubEf0XdicEbZ",
	"R2CxSnBw5g2Y36Ryj+E9DN6DjjsZ9kRMMrp6PPkqQZzCkWbFbmx96+1bv71+d2YtsIAVmZaQA4u0ZA+T",
	"MIRcgZYRQZhSBs12UNvajclxy9NhJaezdDhVjs7baoVu0hAWgqrVlaaTdfgWiABxXqik/ve+MvDPv6+x",
	"a+1akl2tLU6Uyu24QNmCm6RujQ1GDXm1oEIqNJtcXaPzL5dowQUyFQ+ZuRClVCo5QtcJlSjiYZHpJSqR",
	"SgDpqSMF5CYgvkBKFCoJzNqUo1sSfgcWoRec5PRVyCOIgb1EhEVmx/UqhytjD1oIMyBFKEyplv+C58D0",
	"Ie2KtfklIgLQLVcJioGB0EDqcxmiaqSdpioF7VUOIXpvfDr/cok9vAQhrcPj0dlorCPopOMAvx6NR68N",
	"tVViAPf14Oanumzrvzm3NUaT0FQ43b1sVXfzMkj1jkerJ5vyLlqTW/lwKH84aP82Hj+Z6naz6hg0NQ+1",
	"baEGXwP5ZjzuE7q20m/cBcyRs+Ejrfm5mRo4uJl7WBZZRsQKB3jyM0wIi6E58BoKE2SzQ5FY6nTU8vBc",
	"i7IRFhBTqUD0B3nmdphKdJxYV7V/pzifPZnaWmc7vPo5cjXq0dH9/fj3nYmuqoikAki0QlUkB5hShRMR",
	"xOAOFTaqHfQwxc9gHkNX7lOpJnbLgalIFWSDI4VRhct1USdCkFUXKJ8/HJBda5S0d4ikKYLKxQoh92Be",
	"ej35cmGIY+09Wro4OE6bLw2lbcwvDsyVw2JltSPCbLC6YlXz2b9315jSDgIpKNiM4R/meR3DFqBvNkcI",
	"uz96pDf60JvhQ+uXOW33re6t7nvdKTwF1ePi+Pic+fzhl6A1BYVINbBtAaz5cvKmW1e9xa9eXpZzD+dF",
	"B9Rf8+hZFYUTBNi6fMKicBgxZpCnJNy/jPjmerC9T07tllP0yWkF4NH65GEwm8ZqIbPz6SbcdvXQLNzS",
	"my1GR0tDF4LT9uaG0l/cmw/jx3kUIeKu3IpvpceWbPTv3cecHbp8zYbn3OVnkPElVNB0Z0tfk+/xcHx8",
	"8j2HJr8FsEeWF29wa/WhcWAeeD6F6ARc+K/OA/0EenDNbr+lvJnr4EsQy4pehUjd28jA9/WXgjThUgVv",
	"x2/HhihO/n31PVr7YsjW/AYum0+cJeW8/HcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
