// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (event_id, name, email, rsvp_status)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, name, email, rsvp_status, created_at
`

type CreateGuestParams struct {
	EventID    pgtype.UUID
	Name       string
	Email      *string
	RsvpStatus RsvpStatus
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.RsvpStatus,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.RsvpStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuest = `-- name: DeleteGuest :execrows
DELETE FROM guests WHERE id = $1 AND event_id = $2
`

type DeleteGuestParams struct {
	ID      pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) DeleteGuest(ctx context.Context, arg DeleteGuestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuest, arg.ID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGuest = `-- name: GetGuest :one
SELECT id, event_id, name, email, rsvp_status, created_at FROM guests WHERE id = $1 AND event_id = $2
`

type GetGuestParams struct {
	ID      pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) GetGuest(ctx context.Context, arg GetGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, getGuest, arg.ID, arg.EventID)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.RsvpStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listGuestsByEvent = `-- name: ListGuestsByEvent :many
SELECT id, event_id, name, email, rsvp_status, created_at FROM guests WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) ListGuestsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listGuestsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Email,
			&i.RsvpStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuest = `-- name: UpdateGuest :one
UPDATE guests
SET name = $3, email = $4, rsvp_status = $5
WHERE id = $1 AND event_id = $2
RETURNING id, event_id, name, email, rsvp_status, created_at
`

type UpdateGuestParams struct {
	ID         pgtype.UUID
	EventID    pgtype.UUID
	Name       string
	Email      *string
	RsvpStatus RsvpStatus
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, updateGuest,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Email,
		arg.RsvpStatus,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Email,
		&i.RsvpStatus,
		&i.CreatedAt,
	)
	return i, err
}
