// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RsvpStatus string

const (
	RsvpStatusPending  RsvpStatus = "pending"
	RsvpStatusAccepted RsvpStatus = "accepted"
	RsvpStatusDeclined RsvpStatus = "declined"
)

func (e *RsvpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RsvpStatus(s)
	case string:
		*e = RsvpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RsvpStatus: %T", src)
	}
	return nil
}

type NullRsvpStatus struct {
	RsvpStatus RsvpStatus
	Valid      bool // Valid is true if RsvpStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRsvpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RsvpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RsvpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRsvpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RsvpStatus), nil
}

type Event struct {
	ID        pgtype.UUID
	Name      string
	Date      pgtype.Timestamptz
	Location  *string
	CreatedAt pgtype.Timestamptz
}

type Guest struct {
	ID         pgtype.UUID
	EventID    pgtype.UUID
	Name       string
	Email      *string
	RsvpStatus RsvpStatus
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
}
