// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteGuest(ctx context.Context, arg DeleteGuestParams) (int64, error)
	GetEvent(ctx context.Context, id pgtype.UUID) (Event, error)
	GetGuest(ctx context.Context, arg GetGuestParams) (Guest, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListGuestsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Guest, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error)
}

var _ Querier = (*Queries)(nil)
